In [1]:
from datasets import load_dataset

dataset = load_dataset(
    "theatticusproject/cuad",
    verification_mode="no_checks"
)

train_data = dataset["train"]

print("Total Contracts:", len(train_data))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Resolving data files:   0%|          | 0/714 [00:00<?, ?it/s]

Total Contracts: 511

In [2]:
sample = train_data[0]

print(type(sample))

print(sample.keys())

<class 'dict'>
dict_keys(['pdf'])

In [3]:
sample

{'pdf': <pdfplumber.pdf.PDF at 0x20c1024c2f0>}

In [4]:
sample_pdf = train_data[0]["pdf"]

print("Pages:", len(sample_pdf.pages))

Pages: 11

In [5]:
first_page = sample_pdf.pages[0]

text = first_page.extract_text()

print(text[:3000])

Datasheet for Contract Understanding Atticus Dataset (CUAD)
I.MOTIVATION
A. Who created the dataset (e.g., which team, research group) and on behalf of which entity (e.g. company,
institution, organization)?
The Atticus Project is a non-profit organization whose mission is to harness the power of AI to accelerate
accurate and efficient contract review. The Atticus Project started as a grassroots movement by experienced
lawyers in public companies and leading law firms aiming to achieve high-quality, low-cost, accurate and timely
contract review using AI. It was officially incorporated as a California nonprofit public benefit corporation in
January 2020.
B. Did they fund it themselves? If there is an associated grant, please provide the name of the grantor and
the grant name and number.
The Atticus Project relies 100% on unpaid volunteers who are organized around the single mission of changing
the legal industry by leveraging AI.
C. For what purpose was the data set created? Was there a specific task in mind? If so, please specify the
result type (e.g. unit) to be expected.
The original specific task and the intended use case of the dataset is to facilitate the development of accurate AI
algorithms for contract review in corporate transactions. Contract review refers to the process where human
lawyers physically search through hundreds or thousands of contracts to find a few types of legal provisions. This
process is time consuming, costly and prone to human error. The dataset aims to accelerate this process by
leveraging AI. However, as development of this dataset progressed, there has not been any datasets identifying
the different components of a legal contract. We hope that this dataset can be a catalyst to spur development of
AI-models focused on legal contracts that can be an aid for legal practitioners. For example, one use could be an
AI-model that can identify the expiration dates of contracts to remind a party when a contract needs to be
renewed, a product that can generate a disclosure schedule for the seller as part of an acquisition or search for
contracts that should be divested as part of a divestiture.
However, the dataset should not be solely used for contract drafting, contract management, dispute resolution
(incl. litigation) or provision of legal advice. In those situations, qualified human lawyers should still analyze and
review any output. Instead, there are still a number of possibilities that AI can be developed as tools for legal
practitioners and this dataset is intended to spur the development of such tools.
II. COMPOSITION
C. What do the instances (of each type, if appropriate) that comprise the data set represent? (e.g.
documents, photos, people, countries).
Each instance is a commercial contract sourced from the EDGAR (Electronic Data Gathering, Analysis, and
Retrieval) system used by the U.S. Securities and Exchange Commission (SEC). Publicly traded companies in
the United States and some foreign companies are requir

In [6]:
for i in range(5):
    pdf = train_data[i]["pdf"]

    text = pdf.pages[0].extract_text()

    print("\n")
    print("=" * 80)
    print(f"DOCUMENT {i}")
    print("=" * 80)

    print(text[:500])

================================================================================
DOCUMENT 0
================================================================================
Datasheet for Contract Understanding Atticus Dataset (CUAD)
I.MOTIVATION
A. Who created the dataset (e.g., which team, research group) and on behalf of which entity (e.g. company,
institution, organization)?
The Atticus Project is a non-profit organization whose mission is to harness the power of AI to accelerate
accurate and efficient contract review. The Atticus Project started as a grassroots movement by experienced
lawyers in public companies and leading law firms aiming to achieve high-qual


================================================================================
DOCUMENT 1
================================================================================
Exhibit 10.33
Last Updated: April 6, 2007
CHASE AFFILIATE AGREEMENT
THIS AGREEMENT sets forth the terms and conditions agreed to between Chase Bank USA, N.A. (?Chase?) and you as an “Affiliate” in the Chase
Affiliate Program (the “Affiliate Program”). Once accepted into the Affiliate Program, an Affiliate can establish links from the Affiliate’s Website to
[Chase.com]. Chase will pay Affiliate a fee for each approved credit card account that originates from a link in Affiliate’s Website.
THIS IS


================================================================================
DOCUMENT 2
================================================================================
Exhibit 10.27
MARKETING AFFILIATE AGREEMENT
Between:
Birch First Global Investments Inc.
And
Mount Knowledge Holdings Inc.
Dated: May 8, 2014
1
Source: CYBERGY HOLDINGS, INC., 10-Q, 5/20/2014


================================================================================
DOCUMENT 3
================================================================================
DIGITAL CINEMA DESTINATIONS CORP.
NETWORK AFFILIATE AGREEMENT
THIS NETWORK AFFILIATE AGREEMENT (this “Agreement”) is made as of this 14th day of March, 2011 by and between National CineMedia,
LLC, a Delaware limited liability company (“NCM”), and Digital Cinema Destinations Corp., a Delaware corporation (“Network Affiliate” and with
NCM, each a “Party” and collectively, the “Parties”).
BACKGROUND
WHEREAS, NCM operates a “Digital Content Network” of proprietary and third-party hardware and softwa


================================================================================
DOCUMENT 4
================================================================================
EXHIBIT 10.1
AFFLIATE AGREEMENT DATED JULY 15, 2005
AFFILIATE AGREEMENT
This Agreement entered into as of the Effective Date by and between
Link Plus Corporation and Axiometric, LLC.
RECITALS
WHEREAS, Axiometric has developed certain computer software including
wireless mesh networking technology and AMR devices and systems;
WHEREAS, LKPL has developed certain radio devices and systems along
with hardware manufacturing capacities and plans to develop AMR devices and
systems;
WHEREAS, LKPL and Ax

In [7]:
from datasets import load_dataset

dataset = load_dataset(
    "theatticusproject/cuad",
    verification_mode="no_checks"
)

train_data = dataset["train"]

print("Total Contracts:", len(train_data))

Resolving data files:   0%|          | 0/714 [00:00<?, ?it/s]

Total Contracts: 511

In [8]:
contracts = []

for i in range(10):

    pdf = train_data[i]["pdf"]

    text = ""

    for page in pdf.pages:

        page_text = page.extract_text()

        if page_text:
            text += page_text + "\n"

    contracts.append(text)

print("Loaded:", len(contracts))

Loaded: 10

In [9]:
print(contracts[1][:5000])

Exhibit 10.33
Last Updated: April 6, 2007
CHASE AFFILIATE AGREEMENT
THIS AGREEMENT sets forth the terms and conditions agreed to between Chase Bank USA, N.A. (?Chase?) and you as an “Affiliate” in the Chase
Affiliate Program (the “Affiliate Program”). Once accepted into the Affiliate Program, an Affiliate can establish links from the Affiliate’s Website to
[Chase.com]. Chase will pay Affiliate a fee for each approved credit card account that originates from a link in Affiliate’s Website.
THIS IS A LEGAL AND CONTRACTUALLY BINDING AGREEMENT BETWEEN AFFILIATE AND CHASE. TO APPLY TO THE AFFILIATE
PROGRAM, YOU MUST COMPLETE AND SUBMIT THE AFFILIATE REGISTRATION FORM AND CLICK ON THE “AGREE” BUTTON BELOW
TO INDICATE YOUR WILLINGNESS TO BE BOUND TO CHASE BY THIS AGREEMENT. THIS AGREEMENT WILL TAKE EFFECT IF AND
WHEN CHASE REVIEWS AND ACCEPTS YOUR REGISTRATION FORM AND PROVIDES YOU NOTICE OF ACCEPTANCE. BY SUBMITTING
YOUR REGISTRATION FORM, AFFILIATE CERTIFIES THAT YOU HAVE READ AND UNDERSTAND THE TERMS SET FORTH BELOW, AND
THAT YOU ARE AUTHORIZED TO SUBMIT THIS REGISTRATION FORM BY THE NAMED AFFILIATE.
In connection with your participation in the Affiliate Program, Affiliate and Chase agree as follows:
1. Enrollment in the Affiliate Program; Restricted Content
To enroll in the Affiliate Program, you must submit a complete “Affiliate Registration Form” via the Chase Affiliate Website:
For new affiliates: https://ssl.linksynergy.com/php-bin/reg/sregister.shtml?mid=2291
For existing affiliates: http://www.linkshare.com/joinprograms?oid=87909
Chase will evaluate your registration form and will notify you via e-mail of the acceptance or rejection of your registration form. Chase reserves, in
its sole discretion, with or without reason, the right to accept or reject your registration into the Chase Affiliate Program, including but not limited to
a determination that your site is unsuitable for or incompatible with the Affiliate Program based on the following criteria (collectively “Restricted
Content”):
• Incorporates images or content that is any way unlawful, offensive, profane, harmful, threatening, defamatory, obscene, harassing or racially,
ethically or otherwise objectionable
• Promote illegal activities, including gambling
• Promotes or depicts sexually explicit, obscene or pornographic images
• Promotes or depicts violence or hate speech
• Promotes discrimination based on race, sex, religion, nationality, disability, sexual orientation or age
Source: CREDITCARDS.COM, INC., S-1, 8/10/2007
• Incorporates any materials which infringe or assist others to infringe on any copyright, trademark or other intellectual property rights
• Contains or promotes politically sensitive or controversial issues
Chase also reserves the right to terminate this Agreement in the event that any Restricted Content is incorporated on Affiliate’s site after
acceptance of your registration form and the commencement of the term of this Agreement. Chase may also terminate this Agreement if your site is
deemed unsuitable based on the criteria below:
• Manipulates key word searches on portals
• Misrepresents itself as a Chase Website by altering the visual “look and feel” of or text from Chase’s site, and/or engage in “framing” the Chase
Website
• Engages in domain squatting
• Engages in spamming or unsolicited commercial e-mail
• Engages in unauthorized telemarketing or remarketing of Chase Credit Card offers via telephone
• Uses Chase products and services in the domain name, URL or URI, including, but not limited to, any combination of the following words:
• JP
• MORGAN
• CHASE
• MANHATTAN
• AARP
• AMAZON.COM
• BALL STATE UNIVERSITY
• BORDERS
• BRITISH AIRWAYS
• CASH PLUS
• CHASE FREEDOM
• CENTRAL MICHIGAN UNIVERSITY
• CONTINENTAL
• CORNELL UNIVERSITY
• DISNEY
• DUKE UNIVERSITY
• FLEXIBLE REWARDS
• FREE CASH
• HARVARD COOP
• HESS
• HOME IMPROVEMENT
• LEHIGH UNIVERSITY
• LOUISIANA STATE UNIVERSITY
• MARATHON
• MARRIOTT
• MIAMI UNIVERSITY
• OHIO UNIVERSITY
• OVERSTOCK
• PERFECT CARD
• PRIORITY CLUB / HOLIDAY INN
• SONY
• SOUTHERN ILLINOIS UNIVERSITY
• SPEEDWAY SUPER AMERICA
Source: CREDITCARDS.COM, INC., S-1, 8/10/2007
• STARBUCKS
• SUBARU
• TEMPLE UNIVERSITY
• TOYS "R" US
• TRAVEL PLUS
• TRUMP
• ULTIMATE REWARDS
• UNITED
• UNIVERSAL
• UNIVERSITY OF ARIZONA ATHLETICS
• UNIVERSITY OF CHICAGO
• UNIVERSITY OF FLORIDA
• UNIVERSITY OF HOUSTON
• UNIVERSITY OF IDAHO
• UNIVERSITY OF KENTUCKY
• UNIVERSITY OF MARYLAND
• UNIVERSITY OF MEMPHIS
• UNIVERSITY OF MINNESOTA ATHLETICS
• UNIVERSITY OF NOTRE DAME
• UNIVERSITY OF OKLAHOMA
• UNIVERSITY OF OREGON
• UNIVERSITY OF SOUTH CAROLINA
• UNIVERSITY OF TENNESSEE
• UNIVERSITY OF VIRGINIA
• UTAH STATE UNIVERSITY
• VALUE MILES
• VIRGINIA TECH APPROVED ACCOUNT
• VOLKSWAGEN
• WESTERN ILLINOIS UNIVERSITY
• YALE UNIVERSTIY
• Uses a proxy server or redirector server to proxy Chase web pages or web sites through your website, URL or URI
• Otherwise violates intellectual property rights, including, without limitation,

In [10]:
import pandas as pd

data = {
    "text": [
        "Either party may terminate this agreement with 30 days notice.",
        "All confidential information shall remain secret.",
        "Payment shall be made within 30 days.",
        "Employee shall undergo probation for six months.",
        "Employee is entitled to 20 days annual leave.",

        "The agreement can be terminated immediately for breach.",
        "Confidential documents must not be disclosed.",
        "Invoices shall be paid monthly.",
        "Probation period shall be three months.",
        "Employees may avail paid leave."
    ],

    "label": [
        "Termination",
        "Confidentiality",
        "Payment",
        "Probation",
        "Leave Policy",

        "Termination",
        "Confidentiality",
        "Payment",
        "Probation",
        "Leave Policy"
    ]
}

df = pd.DataFrame(data)

df.head()

                                                text            label
0  Either party may terminate this agreement with...      Termination
1  All confidential information shall remain secret.  Confidentiality
2              Payment shall be made within 30 days.          Payment
3   Employee shall undergo probation for six months.        Probation
4      Employee is entitled to 20 days annual leave.     Leave Policy

In [11]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["label_id"] = encoder.fit_transform(df["label"])

df

,text,label,label_id
0,Either party may terminate this agreement with...,Termination,4
1,All confidential information shall remain secret.,Confidentiality,0
2,Payment shall be made within 30 days.,Payment,2
3,Employee shall undergo probation for six months.,Probation,3
4,Employee is entitled to 20 days annual leave.,Leave Policy,1
5,The agreement can be terminated immediately fo...,Termination,4
6,Confidential documents must not be disclosed.,Confidentiality,0
7,Invoices shall be paid monthly.,Payment,2
8,Probation period shall be three months.,Probation,3
9,Employees may avail paid leave.,Leave Policy,1

In [12]:
print(dict(zip(
    encoder.classes_,
    encoder.transform(encoder.classes_)
)))

{'Confidentiality': np.int64(0), 'Leave Policy': np.int64(1), 'Payment': np.int64(2), 'Probation': np.int64(3), 'Termination': np.int64(4)}

In [13]:
pip install transformers datasets torch scikit-learn

Collecting transformers
  Using cached transformers-5.12.1-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: datasets in c:\users\shreeja\anaconda3\lib\site-packages (5.0.0)
Collecting torch
  Using cached torch-2.12.1-cp313-cp313-win_amd64.whl.metadata (31 kB)
Requirement already satisfied: scikit-learn in c:\users\shreeja\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers) (1.19.0)
Requirement already satisfied: numpy>=1.17 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers) (6.0.3)
Collecting regex>=2025.10.22 (from transformers)
  Using cached regex-2026.5.9-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: typer in c:\users\shreeja\anaconda3\lib\site-packages (from transformers) (0.25.1)
Collecting safetensors>=0.4.3 (from transformers)
  Using cached safetensors-0.8.0-cp310-abi3-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: tqdm>=4.60 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: click>=8.4.0 in c:\users\shreeja\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\shreeja\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\shreeja\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in c:\users\shreeja\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\shreeja\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\shreeja\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in c:\users\shreeja\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.10.0)
Requirement already satisfied: certifi in c:\users\shreeja\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\shreeja\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\shreeja\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\shreeja\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\shreeja\anaconda3\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\shreeja\anaconda3\lib\site-packages (from typer->transformers) (14.2.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\shreeja\anaconda3\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (21.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (2.32.5)
Requirement already satisfied: xxhash in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in c:\users\shreeja\anaconda3\lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\shreeja\anaconda3\lib\site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.13.2)
Requirement already satisfied: setuptools<82 in c:\users\shreeja\anaconda3\lib\site-packages (from torch) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\shreeja\anaconda3\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\shreeja\anaconda3\lib\site-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in c:\users\shreeja\anaconda3\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: scipy>=1.8.0 in c:\users\shreeja\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\shreeja\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\shreeja\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\shreeja\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\shreeja\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\shreeja\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\shreeja\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\shreeja\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\shreeja\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\shreeja\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: colorama in c:\users\shreeja\anaconda3\lib\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\shreeja\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\shreeja\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\shreeja\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\shreeja\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\shreeja\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\shreeja\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\shreeja\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\shreeja\anaconda3\lib\site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shreeja\anaconda3\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\shreeja\anaconda3\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shreeja\anaconda3\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\shreeja\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Using cached transformers-5.12.1-py3-none-any.whl (11.2 MB)
Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
Using cached torch-2.12.1-cp313-cp313-win_amd64.whl (123.0 MB)
Using cached regex-2026.5.9-cp313-cp313-win_amd64.whl (277 kB)
Using cached safetensors-0.8.0-cp310-abi3-win_amd64.whl (355 kB)
Installing collected packages: safetensors, regex, torch, tokenizers, transformers

  Attempting uninstall: regex

    Found existing installation: regex 2025.9.1

    Uninstalling regex-2025.9.1:

      Successfully uninstalled regex-2025.9.1

   -------- ------------------------------- 1/5 [regex]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ---------------- ----------------------- 2/5 [torch]
   ------------------------ --------------- 3/5 [tokenizers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]
   -------------------------------- ------- 4/5 [transformers]

In [14]:
from sklearn.model_selection import train_test_split

train_texts, test_texts, train_labels, test_labels = train_test_split(
    df["text"].tolist(),
    df["label_id"].tolist(),
    test_size=0.2,
    random_state=42
)

print("Train Samples:", len(train_texts))
print("Test Samples:", len(test_texts))

Train Samples: 8
Test Samples: 2

In [15]:
from transformers import DistilBertTokenizer

tokenizer = DistilBertTokenizer.from_pretrained(
    "distilbert-base-uncased"
)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

c:\Users\SHREEJA\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:137: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\SHREEJA\.cache\huggingface\hub\models--distilbert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [16]:
train_encodings = tokenizer(
    train_texts,
    truncation=True,
    padding=True,
    max_length=128
)

test_encodings = tokenizer(
    test_texts,
    truncation=True,
    padding=True,
    max_length=128
)

In [17]:
import torch

class ClauseDataset(torch.utils.data.Dataset):

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):

        item = {
            key: torch.tensor(val[idx])
            for key, val in self.encodings.items()
        }

        item["labels"] = torch.tensor(
            self.labels[idx]
        )

        return item

    def __len__(self):
        return len(self.labels)

In [18]:
train_dataset = ClauseDataset(
    train_encodings,
    train_labels
)

test_dataset = ClauseDataset(
    test_encodings,
    test_labels
)

In [19]:
from transformers import DistilBertForSequenceClassification

num_labels = len(encoder.classes_)

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=num_labels
)

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [22]:
pip install -U transformers accelerate

Requirement already satisfied: transformers in c:\users\shreeja\anaconda3\lib\site-packages (5.12.1)
Collecting accelerate
  Downloading accelerate-1.14.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers) (1.19.0)
Requirement already satisfied: numpy>=1.17 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\shreeja\anaconda3\lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: click>=8.4.0 in c:\users\shreeja\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\shreeja\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\shreeja\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in c:\users\shreeja\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\shreeja\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\shreeja\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in c:\users\shreeja\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.10.0)
Requirement already satisfied: certifi in c:\users\shreeja\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\shreeja\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\shreeja\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\shreeja\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\shreeja\anaconda3\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\shreeja\anaconda3\lib\site-packages (from typer->transformers) (14.2.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\shreeja\anaconda3\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: psutil in c:\users\shreeja\anaconda3\lib\site-packages (from accelerate) (7.0.0)
Requirement already satisfied: torch>=2.0.0 in c:\users\shreeja\anaconda3\lib\site-packages (from accelerate) (2.12.1)
Requirement already satisfied: colorama in c:\users\shreeja\anaconda3\lib\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.4.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\shreeja\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\shreeja\anaconda3\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\shreeja\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: setuptools<82 in c:\users\shreeja\anaconda3\lib\site-packages (from torch>=2.0.0->accelerate) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\shreeja\anaconda3\lib\site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\shreeja\anaconda3\lib\site-packages (from torch>=2.0.0->accelerate) (3.5)
Requirement already satisfied: jinja2 in c:\users\shreeja\anaconda3\lib\site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\shreeja\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\shreeja\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\shreeja\anaconda3\lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.2)
Downloading accelerate-1.14.0-py3-none-any.whl (389 kB)
Installing collected packages: accelerate
Successfully installed accelerate-1.14.0
Note: you may need to restart the kernel to use updated packages.

In [23]:
import transformers
import torch
import accelerate

print("Transformers:", transformers.__version__)
print("Torch:", torch.__version__)
print("Accelerate:", accelerate.__version__)

Transformers: 5.12.1
Torch: 2.12.1+cpu
Accelerate: 1.14.0

In [25]:
from transformers import DistilBertTokenizer
from transformers import DistilBertForSequenceClassification

tokenizer = DistilBertTokenizer.from_pretrained(
    "distilbert-base-uncased"
)

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=5
)

print("Model Loaded Successfully")

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model Loaded Successfully

In [27]:
import sys
!{sys.executable} -m pip uninstall transformers -y

Found existing installation: transformers 5.12.1
Uninstalling transformers-5.12.1:
  Successfully uninstalled transformers-5.12.1

In [28]:
pip install transformers==4.55.4

Collecting transformers==4.55.4
  Downloading transformers-4.55.4-py3-none-any.whl.metadata (41 kB)
Requirement already satisfied: filelock in c:\users\shreeja\anaconda3\lib\site-packages (from transformers==4.55.4) (3.20.0)
Collecting huggingface-hub<1.0,>=0.34.0 (from transformers==4.55.4)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers==4.55.4) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers==4.55.4) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers==4.55.4) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers==4.55.4) (2026.5.9)
Requirement already satisfied: requests in c:\users\shreeja\anaconda3\lib\site-packages (from transformers==4.55.4) (2.32.5)
Collecting tokenizers<0.22,>=0.21 (from transformers==4.55.4)
  Downloading tokenizers-0.21.4-cp39-abi3-win_amd64.whl.metadata (6.9 kB)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers==4.55.4) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\shreeja\anaconda3\lib\site-packages (from transformers==4.55.4) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\shreeja\anaconda3\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.55.4) (2025.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\shreeja\anaconda3\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.55.4) (4.15.0)
Requirement already satisfied: colorama in c:\users\shreeja\anaconda3\lib\site-packages (from tqdm>=4.27->transformers==4.55.4) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\shreeja\anaconda3\lib\site-packages (from requests->transformers==4.55.4) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\shreeja\anaconda3\lib\site-packages (from requests->transformers==4.55.4) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\shreeja\anaconda3\lib\site-packages (from requests->transformers==4.55.4) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\shreeja\anaconda3\lib\site-packages (from requests->transformers==4.55.4) (2026.1.4)
Downloading transformers-4.55.4-py3-none-any.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.3 MB 3.6 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/11.3 MB 3.9 MB/s eta 0:00:03
   --------- ------------------------------ 2.6/11.3 MB 4.2 MB/s eta 0:00:03
   ------------- -------------------------- 3.7/11.3 MB 4.3 MB/s eta 0:00:02
   ---------------- ----------------------- 4.7/11.3 MB 4.4 MB/s eta 0:00:02
   ------------------- -------------------- 5.5/11.3 MB 4.4 MB/s eta 0:00:02
   ------------------------ --------------- 6.8/11.3 MB 4.5 MB/s eta 0:00:01
   ---------------------------- ----------- 8.1/11.3 MB 4.7 MB/s eta 0:00:01
   --------------------------------- ------ 9.4/11.3 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 10.5/11.3 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 4.8 MB/s  0:00:02
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ---------------------------------------- 0.0/566.4 kB ? eta -:--:--
   ---------------------------------------- 566.4/566.4 kB 3.5 MB/s  0:00:00
Downloading tokenizers-0.21.4-cp39-abi3-win_amd64.whl (2.5 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.5 MB 1.5 MB/s eta 0:00:02
   ------------------------- -------------- 1.6/2.5 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 2.5/2.5 MB 3.9 MB/s  0:00:00
Installing collected packages: huggingface-hub, tokenizers, transformers

  Attempting uninstall: huggingface-hub

    Found existing installation: huggingface_hub 1.19.0

    Uninstalling huggingface_hub-1.19.0:

      Successfully uninstalled huggingface_hub-1.19.0

   ---------------------------------------- 0/3 [huggingface-hub]
   ---------------------------------------- 0/3 [huggingface-hub]
   ---------------------------------------- 0/3 [huggingface-hub]
   ---------------------------------------- 0/3 [huggingface-hub]
   ---------------------------------------- 0/3 [huggingface-hub]
  Attempting uninstall: tokenizers
   ---------------------------------------- 0/3 [huggingface-hub]
    Found existing installation: tokenizers 0.22.2
   ---------------------------------------- 0/3 [huggingface-hub]
    Uninstalling tokenizers-0.22.2:
   ---------------------------------------- 0/3 [huggingface-hub]
      Successfully uninstalled tokenizers-0.22.2
   ---------------------------------------- 0/3 [huggingface-hub]
   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   ---------------------------------------- 3/3 [transformers]

Successfully installed huggingface-hub-0.36.2 tokenizers-0.21.4 transformers-4.55.4
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\SHREEJA\anaconda3\Lib\site-packages\~okenizers'.
  You can safely remove it manually.

In [29]:
from transformers import DistilBertTokenizer
from transformers import DistilBertForSequenceClassification

tokenizer = DistilBertTokenizer.from_pretrained(
    "distilbert-base-uncased"
)

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=len(encoder.classes_)
)

print("Model Loaded Successfully")

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model Loaded Successfully

In [31]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",

    num_train_epochs=3,

    per_device_train_batch_size=2,

    per_device_eval_batch_size=2,

    logging_steps=1,

    save_strategy="no",

    report_to="none"
)

ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=1.1.0`: Please run `pip install transformers[torch]` or `pip install 'accelerate>=1.1.0'`

In [32]:
from transformers import TrainingArguments

try:
    training_args = TrainingArguments(
        output_dir="./results"
    )
    print("SUCCESS")
except Exception as e:
    import traceback
    traceback.print_exc()

Traceback (most recent call last):
  File "C:\Users\SHREEJA\AppData\Local\Temp\ipykernel_10784\3721582227.py", line 4, in <module>
    training_args = TrainingArguments(
        output_dir="./results"
    )
  File "<string>", line 115, in __init__
  File "c:\Users\SHREEJA\anaconda3\Lib\site-packages\transformers\training_args.py", line 1599, in __post_init__
  File "c:\Users\SHREEJA\anaconda3\Lib\site-packages\transformers\training_args.py", line 1890, in device
    raise ValueError("warmup_ratio must lie in range [0,1]")
       ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\SHREEJA\anaconda3\Lib\functools.py", line 1026, in __get__
    val = self.func(instance)
  File "c:\Users\SHREEJA\anaconda3\Lib\site-packages\transformers\training_args.py", line 1778, in _setup_devices
    elif isinstance(self.accelerator_config, type):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
            "Please pass in a fully constructed `AcceleratorConfig` object instead."

ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=1.1.0`: Please run `pip install transformers[torch]` or `pip install 'accelerate>=1.1.0'`

In [33]:
from transformers import DistilBertForSequenceClassification

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=len(encoder.classes_)
)

print("Model Loaded Successfully")

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model Loaded Successfully

In [1]:
sample_pdf = train_data[1]["pdf"]

print("Pages:", len(sample_pdf.pages))

for i in range(min(3, len(sample_pdf.pages))):
    print("\n" + "="*80)
    print(f"PAGE {i+1}")
    print("="*80)

    text = sample_pdf.pages[i].extract_text()

    if text:
        print(text[:2000])

NameError: name 'train_data' is not defined

In [2]:
from datasets import load_dataset

dataset = load_dataset(
    "theatticusproject/cuad",
    verification_mode="no_checks"
)

train_data = dataset["train"]

print("Total Contracts:", len(train_data))

Resolving data files:   0%|          | 0/714 [00:00<?, ?it/s]

Total Contracts: 511

In [3]:
sample_pdf = train_data[1]["pdf"]

print("Pages:", len(sample_pdf.pages))

Pages: 12

In [4]:
for i in range(min(3, len(sample_pdf.pages))):

    print("\n" + "="*80)
    print(f"PAGE {i+1}")
    print("="*80)

    text = sample_pdf.pages[i].extract_text()

    if text:
        print(text[:2000])

================================================================================
PAGE 1
================================================================================
Exhibit 10.33
Last Updated: April 6, 2007
CHASE AFFILIATE AGREEMENT
THIS AGREEMENT sets forth the terms and conditions agreed to between Chase Bank USA, N.A. (?Chase?) and you as an “Affiliate” in the Chase
Affiliate Program (the “Affiliate Program”). Once accepted into the Affiliate Program, an Affiliate can establish links from the Affiliate’s Website to
[Chase.com]. Chase will pay Affiliate a fee for each approved credit card account that originates from a link in Affiliate’s Website.
THIS IS A LEGAL AND CONTRACTUALLY BINDING AGREEMENT BETWEEN AFFILIATE AND CHASE. TO APPLY TO THE AFFILIATE
PROGRAM, YOU MUST COMPLETE AND SUBMIT THE AFFILIATE REGISTRATION FORM AND CLICK ON THE “AGREE” BUTTON BELOW
TO INDICATE YOUR WILLINGNESS TO BE BOUND TO CHASE BY THIS AGREEMENT. THIS AGREEMENT WILL TAKE EFFECT IF AND
WHEN CHASE REVIEWS AND ACCEPTS YOUR REGISTRATION FORM AND PROVIDES YOU NOTICE OF ACCEPTANCE. BY SUBMITTING
YOUR REGISTRATION FORM, AFFILIATE CERTIFIES THAT YOU HAVE READ AND UNDERSTAND THE TERMS SET FORTH BELOW, AND
THAT YOU ARE AUTHORIZED TO SUBMIT THIS REGISTRATION FORM BY THE NAMED AFFILIATE.
In connection with your participation in the Affiliate Program, Affiliate and Chase agree as follows:
1. Enrollment in the Affiliate Program; Restricted Content
To enroll in the Affiliate Program, you must submit a complete “Affiliate Registration Form” via the Chase Affiliate Website:
For new affiliates: https://ssl.linksynergy.com/php-bin/reg/sregister.shtml?mid=2291
For existing affiliates: http://www.linkshare.com/joinprograms?oid=87909
Chase will evaluate your registration form and will notify you via e-mail of the acceptance or rejection of your registration form. Chase reserves, in
its sole discretion, with or without reason, the right to accept or reject your registration into the Chase Affiliate Program, including but not limited to
a determination that your site is unsuitable for or incompatible with the Affiliate Program based on the following criteria (collective

================================================================================
PAGE 2
================================================================================
• Incorporates any materials which infringe or assist others to infringe on any copyright, trademark or other intellectual property rights
• Contains or promotes politically sensitive or controversial issues
Chase also reserves the right to terminate this Agreement in the event that any Restricted Content is incorporated on Affiliate’s site after
acceptance of your registration form and the commencement of the term of this Agreement. Chase may also terminate this Agreement if your site is
deemed unsuitable based on the criteria below:
• Manipulates key word searches on portals
• Misrepresents itself as a Chase Website by altering the visual “look and feel” of or text from Chase’s site, and/or engage in “framing” the Chase
Website
• Engages in domain squatting
• Engages in spamming or unsolicited commercial e-mail
• Engages in unauthorized telemarketing or remarketing of Chase Credit Card offers via telephone
• Uses Chase products and services in the domain name, URL or URI, including, but not limited to, any combination of the following words:
• JP
• MORGAN
• CHASE
• MANHATTAN
• AARP
• AMAZON.COM
• BALL STATE UNIVERSITY
• BORDERS
• BRITISH AIRWAYS
• CASH PLUS
• CHASE FREEDOM
• CENTRAL MICHIGAN UNIVERSITY
• CONTINENTAL
• CORNELL UNIVERSITY
• DISNEY
• DUKE UNIVERSITY
• FLEXIBLE REWARDS
• FREE CASH
• HARVARD COOP
• HESS
• HOME IMPROVEMENT
• LEHIGH UNIVERSITY
• LOUISIANA STATE UNIVERSITY
• MARATHON
• MARRIOTT
• MIAMI UNIVERSITY
• OHIO UNIVERSITY
• OVERSTOCK
• PERFECT CARD
• PRIORITY CLUB / HOLIDAY INN
• SONY
• SOUTHERN ILLINOIS UNIVERSITY
• SPEEDWAY SUPER AMERICA
Source: CREDITCARDS.COM, INC., S-1, 8/10/2007

================================================================================
PAGE 3
================================================================================
• STARBUCKS
• SUBARU
• TEMPLE UNIVERSITY
• TOYS "R" US
• TRAVEL PLUS
• TRUMP
• ULTIMATE REWARDS
• UNITED
• UNIVERSAL
• UNIVERSITY OF ARIZONA ATHLETICS
• UNIVERSITY OF CHICAGO
• UNIVERSITY OF FLORIDA
• UNIVERSITY OF HOUSTON
• UNIVERSITY OF IDAHO
• UNIVERSITY OF KENTUCKY
• UNIVERSITY OF MARYLAND
• UNIVERSITY OF MEMPHIS
• UNIVERSITY OF MINNESOTA ATHLETICS
• UNIVERSITY OF NOTRE DAME
• UNIVERSITY OF OKLAHOMA
• UNIVERSITY OF OREGON
• UNIVERSITY OF SOUTH CAROLINA
• UNIVERSITY OF TENNESSEE
• UNIVERSITY OF VIRGINIA
• UTAH STATE UNIVERSITY
• VALUE MILES
• VIRGINIA TECH APPROVED ACCOUNT
• VOLKSWAGEN
• WESTERN ILLINOIS UNIVERSITY
• YALE UNIVERSTIY
• Uses a proxy server or redirector server to proxy Chase web pages or web sites through your website, URL or URI
• Otherwise violates intellectual property rights, including, without limitation, “scraping” text or images from Chase’s Website
• Does not clearly state an online privacy policy to its visitors
• Is based outside of the United States
• Is otherwise considered offensive or inappropriate, at Chase’s discretion
2. Affiliate Responsibilities:
• Affiliate cannot use or implement creative that is not available through the LinkShare affiliate interface.
• Affiliates may not harvest or collect personal information, or email addresses using the Chase brand without the written consent of Chase
• If Affiliate manages a sub-affiliate network, upon Chase’s request, Affiliate shall promptly provide Chase with a current, written list identifying the
sub-affiliates or other third parties associated.
• Chase reserves the right to review and approve all sub-affiliate partners.
• Chase shall only use the list for the sole purpose of administering the program and monitoring proper usage, and will not poach or contact
subaffiliates directly.
• Affiliates will not use the following product keyword search terms. (See Appendix)
Source: CREDITCARDS.COM, INC., S-1, 8/10/2007

In [5]:
pdf = train_data[1]["pdf"]

full_text = ""

for page in pdf.pages:

    page_text = page.extract_text()

    if page_text:
        full_text += page_text + "\n"

print("Characters:", len(full_text))

Characters: 28554

In [6]:
print(full_text[:10000])

Exhibit 10.33
Last Updated: April 6, 2007
CHASE AFFILIATE AGREEMENT
THIS AGREEMENT sets forth the terms and conditions agreed to between Chase Bank USA, N.A. (?Chase?) and you as an “Affiliate” in the Chase
Affiliate Program (the “Affiliate Program”). Once accepted into the Affiliate Program, an Affiliate can establish links from the Affiliate’s Website to
[Chase.com]. Chase will pay Affiliate a fee for each approved credit card account that originates from a link in Affiliate’s Website.
THIS IS A LEGAL AND CONTRACTUALLY BINDING AGREEMENT BETWEEN AFFILIATE AND CHASE. TO APPLY TO THE AFFILIATE
PROGRAM, YOU MUST COMPLETE AND SUBMIT THE AFFILIATE REGISTRATION FORM AND CLICK ON THE “AGREE” BUTTON BELOW
TO INDICATE YOUR WILLINGNESS TO BE BOUND TO CHASE BY THIS AGREEMENT. THIS AGREEMENT WILL TAKE EFFECT IF AND
WHEN CHASE REVIEWS AND ACCEPTS YOUR REGISTRATION FORM AND PROVIDES YOU NOTICE OF ACCEPTANCE. BY SUBMITTING
YOUR REGISTRATION FORM, AFFILIATE CERTIFIES THAT YOU HAVE READ AND UNDERSTAND THE TERMS SET FORTH BELOW, AND
THAT YOU ARE AUTHORIZED TO SUBMIT THIS REGISTRATION FORM BY THE NAMED AFFILIATE.
In connection with your participation in the Affiliate Program, Affiliate and Chase agree as follows:
1. Enrollment in the Affiliate Program; Restricted Content
To enroll in the Affiliate Program, you must submit a complete “Affiliate Registration Form” via the Chase Affiliate Website:
For new affiliates: https://ssl.linksynergy.com/php-bin/reg/sregister.shtml?mid=2291
For existing affiliates: http://www.linkshare.com/joinprograms?oid=87909
Chase will evaluate your registration form and will notify you via e-mail of the acceptance or rejection of your registration form. Chase reserves, in
its sole discretion, with or without reason, the right to accept or reject your registration into the Chase Affiliate Program, including but not limited to
a determination that your site is unsuitable for or incompatible with the Affiliate Program based on the following criteria (collectively “Restricted
Content”):
• Incorporates images or content that is any way unlawful, offensive, profane, harmful, threatening, defamatory, obscene, harassing or racially,
ethically or otherwise objectionable
• Promote illegal activities, including gambling
• Promotes or depicts sexually explicit, obscene or pornographic images
• Promotes or depicts violence or hate speech
• Promotes discrimination based on race, sex, religion, nationality, disability, sexual orientation or age
Source: CREDITCARDS.COM, INC., S-1, 8/10/2007
• Incorporates any materials which infringe or assist others to infringe on any copyright, trademark or other intellectual property rights
• Contains or promotes politically sensitive or controversial issues
Chase also reserves the right to terminate this Agreement in the event that any Restricted Content is incorporated on Affiliate’s site after
acceptance of your registration form and the commencement of the term of this Agreement. Chase may also terminate this Agreement if your site is
deemed unsuitable based on the criteria below:
• Manipulates key word searches on portals
• Misrepresents itself as a Chase Website by altering the visual “look and feel” of or text from Chase’s site, and/or engage in “framing” the Chase
Website
• Engages in domain squatting
• Engages in spamming or unsolicited commercial e-mail
• Engages in unauthorized telemarketing or remarketing of Chase Credit Card offers via telephone
• Uses Chase products and services in the domain name, URL or URI, including, but not limited to, any combination of the following words:
• JP
• MORGAN
• CHASE
• MANHATTAN
• AARP
• AMAZON.COM
• BALL STATE UNIVERSITY
• BORDERS
• BRITISH AIRWAYS
• CASH PLUS
• CHASE FREEDOM
• CENTRAL MICHIGAN UNIVERSITY
• CONTINENTAL
• CORNELL UNIVERSITY
• DISNEY
• DUKE UNIVERSITY
• FLEXIBLE REWARDS
• FREE CASH
• HARVARD COOP
• HESS
• HOME IMPROVEMENT
• LEHIGH UNIVERSITY
• LOUISIANA STATE UNIVERSITY
• MARATHON
• MARRIOTT
• MIAMI UNIVERSITY
• OHIO UNIVERSITY
• OVERSTOCK
• PERFECT CARD
• PRIORITY CLUB / HOLIDAY INN
• SONY
• SOUTHERN ILLINOIS UNIVERSITY
• SPEEDWAY SUPER AMERICA
Source: CREDITCARDS.COM, INC., S-1, 8/10/2007
• STARBUCKS
• SUBARU
• TEMPLE UNIVERSITY
• TOYS "R" US
• TRAVEL PLUS
• TRUMP
• ULTIMATE REWARDS
• UNITED
• UNIVERSAL
• UNIVERSITY OF ARIZONA ATHLETICS
• UNIVERSITY OF CHICAGO
• UNIVERSITY OF FLORIDA
• UNIVERSITY OF HOUSTON
• UNIVERSITY OF IDAHO
• UNIVERSITY OF KENTUCKY
• UNIVERSITY OF MARYLAND
• UNIVERSITY OF MEMPHIS
• UNIVERSITY OF MINNESOTA ATHLETICS
• UNIVERSITY OF NOTRE DAME
• UNIVERSITY OF OKLAHOMA
• UNIVERSITY OF OREGON
• UNIVERSITY OF SOUTH CAROLINA
• UNIVERSITY OF TENNESSEE
• UNIVERSITY OF VIRGINIA
• UTAH STATE UNIVERSITY
• VALUE MILES
• VIRGINIA TECH APPROVED ACCOUNT
• VOLKSWAGEN
• WESTERN ILLINOIS UNIVERSITY
• YALE UNIVERSTIY
• Uses a proxy server or redirector server to proxy Chase web pages or web sites through your website, URL or URI
• Otherwise violates intellectual property rights, including, without limitation, “scraping” text or images from Chase’s Website
• Does not clearly state an online privacy policy to its visitors
• Is based outside of the United States
• Is otherwise considered offensive or inappropriate, at Chase’s discretion
2. Affiliate Responsibilities:
• Affiliate cannot use or implement creative that is not available through the LinkShare affiliate interface.
• Affiliates may not harvest or collect personal information, or email addresses using the Chase brand without the written consent of Chase
• If Affiliate manages a sub-affiliate network, upon Chase’s request, Affiliate shall promptly provide Chase with a current, written list identifying the
sub-affiliates or other third parties associated.
• Chase reserves the right to review and approve all sub-affiliate partners.
• Chase shall only use the list for the sole purpose of administering the program and monitoring proper usage, and will not poach or contact
subaffiliates directly.
• Affiliates will not use the following product keyword search terms. (See Appendix)
Source: CREDITCARDS.COM, INC., S-1, 8/10/2007
• If Affiliate manages a sub-affiliate network, the Affiliate may not pay sub-affiliates or other partners higher referral fees than the lowest tier of the
public offer ($55.00).
• Affiliate is prohibited from (a) installing spyware on another person’s computer, (b) causing spyware to be installed on another person’s
computer, or (c) using a context based triggering mechanism to display an advertisement that partially or wholly covers or obscures paid
advertising or other content on an Internet website in a way that interferes with a user’s ability to view the Internet website.
3. Referral Fee
For each Approved Account (as defined in section 4 below) received through Affiliate’s site, Affiliate will earn a referral fee calculated in
accordance with the schedule set forth below (“Commission”) paid monthly.
• Tiered or flat commission based on private offer terms in the network.
Chase reserves the right to alter above referral fees from time to time upon written notice to Affiliate of such change.
4. Approved Account
For purposes of determining Affiliate’s Commission, an “Approved Account” means any Chase credit card application that is: (i) submitted by any
user who clicks on an e-mail, banner or any other advertising material from Affiliate’s Website; (ii) is approved by Chase; and (iii) is reported as
approved by Chase to Affiliate.
5.Term of this Agreement
The term of this Agreement will commence on the date that the Affiliate Registration Form is approved by Chase and will end when terminated by
either party. Either Affiliate or Chase may terminate this Agreement at any time, with or without cause, by giving the other party written or e-mail
notice of termination. At the time of termination, any links to Chase’s Website must be removed immediately. Affiliate will continue to receive
Commission payments for all Approved Accounts placed during the term of this Agreement. Notwithstanding the foregoing, Chase may
terminate this Agreement if Affiliate does not comply with the terms and conditions herein.
6. Links
Affiliate agrees to place Chase’s links provided by Linkshare NetworkTM which manages the Affiliate Program (“Links”) on its Affiliate’s website.
Affiliate is responsible for obtaining prior written approval from the Chase Affiliate manager or Linkshare Network to link any or all other sites
owned or managed by the Affiliate, other than the site that was approved at the time of original registration. Affiliate may select or remove Links, at
any time without prior approval from Chase. Affiliate is also responsible for removing and/or informing Chase of potential inactive or misdirected
Links. Affiliate agrees to cooperate with Chase in establishing and maintaining Links.
Source: CREDITCARDS.COM, INC., S-1, 8/10/2007
7. Order Processing
Chase will be solely responsible for processing each order placed by a customer from Affiliate’s Links. Customers may only use the Chase on-line
application process to apply for a Chase credit card. “Customers” are defined herein as individuals who apply for Chase credit cards through a link
in Affiliate’s Web site. Chase shall be responsible for administering application forms and related customer service. All of the rules, operating
procedures and policies of Chase regarding customer orders and accounts will apply to orders received through the Links. Chase reserves the right
to reject any credit card application in its sole discretion.
8. Tracking of Sales
Chase will be solely responsible for tracking Approved Accounts made to customers who follow Affiliate’s Links. Affiliate will be solely
responsible for ensuring that the Links are formatted properly and maintained in a manner, which allows Chase to track such Approved Accounts.
No Commission shall be paid if the Approved Account cannot be tracked by Chase’s system or if the customer accesses the Chase site through
means other than the Links. Chase

In [7]:
import re

headings = re.findall(
    r"\n\d+\.\s+[A-Za-z].+",
    full_text
)

print("Total Headings:", len(headings))

for h in headings[:20]:
    print(h)

Total Headings: 22

1. Enrollment in the Affiliate Program; Restricted Content

2. Affiliate Responsibilities:

3. Referral Fee

4. Approved Account

6. Links

7. Order Processing

8. Tracking of Sales

9. Terms and Conditions of Credit Cards

10. Chase Customers

11. Product Descriptions

12. Copyrighted Material

13. Commercial Use

14. Trademarks

15. Licenses and Use of the Chase Logos and Trademarks

16. Service Interruption

17. Indemnification

18. Confidentiality

19. Modification

20. Warranty Disclaimer

21. Limitation of Damages

In [8]:
import re

pattern = r"\n(\d+\.\s+[^\n]+)"

matches = list(re.finditer(pattern, full_text))

print("Sections Found:", len(matches))

Sections Found: 22

In [9]:
clauses = []

for i in range(len(matches)):

    start = matches[i].start()

    title = matches[i].group(1)

    if i < len(matches) - 1:
        end = matches[i + 1].start()
    else:
        end = len(full_text)

    section_text = full_text[start:end]

    clauses.append({
        "label": title,
        "text": section_text
    })

print("Total Clauses:", len(clauses))

Total Clauses: 22

In [10]:
for clause in clauses[:3]:

    print("="*80)

    print("LABEL:")
    print(clause["label"])

    print("\nTEXT:")
    print(clause["text"][:500])

================================================================================
LABEL:
1. Enrollment in the Affiliate Program; Restricted Content

TEXT:

1. Enrollment in the Affiliate Program; Restricted Content
To enroll in the Affiliate Program, you must submit a complete “Affiliate Registration Form” via the Chase Affiliate Website:
For new affiliates: https://ssl.linksynergy.com/php-bin/reg/sregister.shtml?mid=2291
For existing affiliates: http://www.linkshare.com/joinprograms?oid=87909
Chase will evaluate your registration form and will notify you via e-mail of the acceptance or rejection of your registration form. Chase reserves, in
its s
================================================================================
LABEL:
2. Affiliate Responsibilities:

TEXT:

2. Affiliate Responsibilities:
• Affiliate cannot use or implement creative that is not available through the LinkShare affiliate interface.
• Affiliates may not harvest or collect personal information, or email addresses using the Chase brand without the written consent of Chase
• If Affiliate manages a sub-affiliate network, upon Chase’s request, Affiliate shall promptly provide Chase with a current, written list identifying the
sub-affiliates or other third parties associated.
• Chase reserv
================================================================================
LABEL:
3. Referral Fee

TEXT:

3. Referral Fee
For each Approved Account (as defined in section 4 below) received through Affiliate’s site, Affiliate will earn a referral fee calculated in
accordance with the schedule set forth below (“Commission”) paid monthly.
• Tiered or flat commission based on private offer terms in the network.
Chase reserves the right to alter above referral fees from time to time upon written notice to Affiliate of such change.

In [11]:
import pandas as pd

df = pd.DataFrame(clauses)

df.head()

,label,text
0,1. Enrollment in the Affiliate Program; Restri...,\n1. Enrollment in the Affiliate Program; Rest...
1,2. Affiliate Responsibilities:,\n2. Affiliate Responsibilities:\n• Affiliate ...
2,3. Referral Fee,\n3. Referral Fee\nFor each Approved Account (...
3,4. Approved Account,\n4. Approved Account\nFor purposes of determi...
4,6. Links,\n6. Links\nAffiliate agrees to place Chase’s ...

In [12]:
import pandas as pd

df = pd.DataFrame(clauses)

df.head()

,label,text
0,1. Enrollment in the Affiliate Program; Restri...,\n1. Enrollment in the Affiliate Program; Rest...
1,2. Affiliate Responsibilities:,\n2. Affiliate Responsibilities:\n• Affiliate ...
2,3. Referral Fee,\n3. Referral Fee\nFor each Approved Account (...
3,4. Approved Account,\n4. Approved Account\nFor purposes of determi...
4,6. Links,\n6. Links\nAffiliate agrees to place Chase’s ...

In [13]:
df["label"] = df["label"].str.replace(
    r"^\d+\.\s*",
    "",
    regex=True
)

df.head()

,label,text
0,Enrollment in the Affiliate Program; Restricte...,\n1. Enrollment in the Affiliate Program; Rest...
1,Affiliate Responsibilities:,\n2. Affiliate Responsibilities:\n• Affiliate ...
2,Referral Fee,\n3. Referral Fee\nFor each Approved Account (...
3,Approved Account,\n4. Approved Account\nFor purposes of determi...
4,Links,\n6. Links\nAffiliate agrees to place Chase’s ...

In [14]:
df.to_csv(
    "cuad_training.csv",
    index=False
)

print("Dataset Saved")

Dataset Saved

In [15]:
df.head()

,label,text
0,Enrollment in the Affiliate Program; Restricte...,\n1. Enrollment in the Affiliate Program; Rest...
1,Affiliate Responsibilities:,\n2. Affiliate Responsibilities:\n• Affiliate ...
2,Referral Fee,\n3. Referral Fee\nFor each Approved Account (...
3,Approved Account,\n4. Approved Account\nFor purposes of determi...
4,Links,\n6. Links\nAffiliate agrees to place Chase’s ...

In [16]:
df["label"].value_counts()

label
Enrollment in the Affiliate Program; Restricted Content    1
Affiliate Responsibilities:                                1
Independent Investigation                                  1
Limitation of Damages                                      1
Warranty Disclaimer                                        1
Modification                                               1
Confidentiality                                            1
Indemnification                                            1
Service Interruption                                       1
Licenses and Use of the Chase Logos and Trademarks         1
Trademarks                                                 1
Commercial Use                                             1
Copyrighted Material                                       1
Product Descriptions                                       1
Chase Customers                                            1
Terms and Conditions of Credit Cards                       1
Tracking of Sales                                          1
Order Processing                                           1
Links                                                      1
Approved Account                                           1
Referral Fee                                               1
Governing Law                                              1
Name: count, dtype: int64

In [17]:
import os

print(os.getcwd())

d:\contract-intelligence-ai\notebooks

In [18]:
df.to_csv(
    "../data/processed/cuad_training.csv",
    index=False
)

In [19]:
import os

print(
    os.path.exists(
        "../data/processed/cuad_training.csv"
    )
)

True

In [22]:
import pandas as pd

df = pd.read_csv(
    "data/processed/cuad_training.csv"
)

print(df["label"].tolist()[:20])

FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/cuad_training.csv'

In [23]:
import pandas as pd

df = pd.read_csv(
    r"D:\contract-intelligence-ai\data\processed\cuad_training.csv"
)

print(df.head())

                                               label  \
0                                           Parties.
1  Description Of Premises. Thepremises (the "Pre...
2  Purchase Price. ThepurchasepriceforthePremises...
3  Escrow. All funds deposited or paid by the BUY...
4  Time For Performance. The SELLER shall deliver...

                                                text
0  1. Parties.\n[insert name],\nthe "SELLER," agr...
1  2. Description Of Premises. Thepremises (the "...
2  3. Purchase Price. ThepurchasepriceforthePremi...
3  4. Escrow. All funds deposited or paid by the ...
4  5. Time For Performance. The SELLER shall deli...

In [24]:
for label in sorted(df["label"].unique()):
    print(label)

ACKNOWLEDGMENT. CONSULTANT shall acknowledge in all reports and literature that the material is
APPROVED AS TO INSURANCE: 4. APPROVED AS TO FORM:
AUDIT REVIEW PROCEDURES
Acceptance Of Deed. The BUYER shall have the right to accept such title to the Premises as the SELLER
Accommodation
Acknowledgment Of Fee Due Broker. The SELLER and BUYER acknowledge that a fee of
Additional Provisions.
Adjustments. At the time for performance of this Agreement adjustments shall be made as of the date of
Annual Leave (See Guideline 10)
Buyer's Default. If the BUYER or BUYER'S nominee breaches this Agreement, all escrowed funds paid or
Buyer's Financing. (Delete if Waived) The BUYER'S obligation to purchase is conditioned upon obtaining
COMPENSATION.
COMPLETE AGREEMENT
CONSULTANT 2. SANTA CRUZ COUNTY REGIONAL
CONSULTANT's final invoice must be submitted within 60-calendar days after
Closing Certifications and Documents. The SELLER shall execute and deliver simultaneously with the
Clothing (Delete this clause if not applicable)
Commencement
Common Interest Agreement. To the extent that any Confidential Information
Counterparts / Facsimiles / Construction Of Agreement. This Agreement may be executed in
DISPUTES. This Agreement shall be construed under the laws of the State of California. Pending final
DUTIES.
Deductions from remuneration (See Guideline 14)
Definition of Confidential Information. “Confidential Information” means
Description Of Premises. Thepremises (the "Premises")consist oftheland containing approximately
EARLY TERMINATION.
EQUAL EMPLOYMENT OPPORTUNITY. During and in relation to the performance of this Agreement,
Escrow. All funds deposited or paid by the BUYER shall be held in a non-interest bearing escrow account,
Exceptions. Notwithstanding the above, information disclosed hereunder shall
Extension Of Time For Performance. If the SELLER cannot convey title as required by this Agreement or
FEDERAL, STATE AND LOCAL LAWS. CONSULTANT warrants that in the performance of this
Family responsibility leave (See Guideline 13)
General
HARASSMENT. The COMMISSION maintains a strict policy prohibiting unlawful harassment, including
Hours of work (See Guideline 6)
INDEMNIFICATION FOR DAMAGES, TAXES AND CONTRIBUTIONS.
INDEPENDENT CONSULTANT STATUS. CONSULTANT and COMMISSION have reviewed and
INSPECTION OF WORK
INSURANCE. CONSULTANT, at its sole cost and expense, for the full term of this Agreement, and any
Independent Contractors. The parties are independent contractors, and nothing
Itemized expenses incurred during the billing period;
Job description
LICENSES. If a license of any kind is required of CONSULTANT, its employees, agents, or sub
Labor (staff name, hours charged, hourly billing rate, current charges and cumulative
MODIFICATION OF AGREEMENT.
Maternity leave (See Guideline 12)
Meal Intervals (See Guideline 7)
Miscellaneous.
NONASSIGNMENT. The CONSULTANT shall not assign the Agreement without the prior written consent
NOTIFICATION. All notices hereunder and communications regarding interpretation of the terms of this
No Representations Made. Recipient acknowledges that neither Discloser, nor
No Rights Granted. Nothing in this Agreement shall be construed as granting
Nondisclosure of Confidential Information. Recipient shall not use any
Notice of Compelled Disclosure. In the event that Recipient or any person to
Notices. All notices required or permitted to be made under this Agreement shall be in writing and delivered
Other conditions of employment or benefits
Parties.
Place of work
Possession And Condition Of Premises. At the time for performance the Premises also shall comply with
Public Holidays (See Guideline 9)
Purchase Price. ThepurchasepriceforthePremises is $
REBATES, KICKBACKS OR OTHER UNLAWFUL CONSIDERATION. The CONSULTANT
RETENTION AND AUDIT OF RECORDS. For the purpose of determining compliance with Public
Remedies. Each party’s obligations set forth in this Agreement are necessary and
Report of expenditures by CONSULTANT and subconsultants for each task and subtask
Return of Materials. Recipient shall, except as otherwise expressly authorized
SAFETY
SUBCONTRACTING
Sick leave (See Guideline 11)
Sunday work (See Guideline 8)
TERM. This Agreement shall take effect on (DATE); contingent upon prior approval by the
Term. The foregoing commitments of each party shall survive any termination of
Termination of employment (See Guidelines 2 and 3)
Tests/Survey. (Delete If Waived) The BUYER'S obligations under this Agreement are subject to BUYER'S
Time For Performance. The SELLER shall deliver the deed and the BUYER shall pay the balance of the
Title Insurance. BUYER'S obligations are contingent upon the availability (at normal premium rates) of an
Title/Plans. The SELLER shall convey the Premises by a good and sufficient quitclaim deed running to the
Total amount previously paid under this Agreement;
Total invoice/payment requested;
WORK PRODUCTS. All material, data, information, and written, graphic or other work produced under
Wage (See Guidelines 4 and 5)
Warranties And Representations. The SELLER further represents and warrants that SELLER has full
Written progress reports, in a format to be mutually agreed upon, that is sufficiently

In [25]:
labels = sorted(df["label"].unique())

print("Total Labels:", len(labels))

for i, label in enumerate(labels):
    print(f"{i+1}. {label}")

Total Labels: 83
1. ACKNOWLEDGMENT. CONSULTANT shall acknowledge in all reports and literature that the material is
2. APPROVED AS TO INSURANCE: 4. APPROVED AS TO FORM:
3. AUDIT REVIEW PROCEDURES
4. Acceptance Of Deed. The BUYER shall have the right to accept such title to the Premises as the SELLER
5. Accommodation
6. Acknowledgment Of Fee Due Broker. The SELLER and BUYER acknowledge that a fee of
7. Additional Provisions.
8. Adjustments. At the time for performance of this Agreement adjustments shall be made as of the date of
9. Annual Leave (See Guideline 10)
10. Buyer's Default. If the BUYER or BUYER'S nominee breaches this Agreement, all escrowed funds paid or
11. Buyer's Financing. (Delete if Waived) The BUYER'S obligation to purchase is conditioned upon obtaining
12. COMPENSATION.
13. COMPLETE AGREEMENT
14. CONSULTANT 2. SANTA CRUZ COUNTY REGIONAL
15. CONSULTANT's final invoice must be submitted within 60-calendar days after
16. Closing Certifications and Documents. The SELLER shall execute and deliver simultaneously with the
17. Clothing (Delete this clause if not applicable)
18. Commencement
19. Common Interest Agreement. To the extent that any Confidential Information
20. Counterparts / Facsimiles / Construction Of Agreement. This Agreement may be executed in
21. DISPUTES. This Agreement shall be construed under the laws of the State of California. Pending final
22. DUTIES.
23. Deductions from remuneration (See Guideline 14)
24. Definition of Confidential Information. “Confidential Information” means
25. Description Of Premises. Thepremises (the "Premises")consist oftheland containing approximately
26. EARLY TERMINATION.
27. EQUAL EMPLOYMENT OPPORTUNITY. During and in relation to the performance of this Agreement,
28. Escrow. All funds deposited or paid by the BUYER shall be held in a non-interest bearing escrow account,
29. Exceptions. Notwithstanding the above, information disclosed hereunder shall
30. Extension Of Time For Performance. If the SELLER cannot convey title as required by this Agreement or
31. FEDERAL, STATE AND LOCAL LAWS. CONSULTANT warrants that in the performance of this
32. Family responsibility leave (See Guideline 13)
33. General
34. HARASSMENT. The COMMISSION maintains a strict policy prohibiting unlawful harassment, including
35. Hours of work (See Guideline 6)
36. INDEMNIFICATION FOR DAMAGES, TAXES AND CONTRIBUTIONS.
37. INDEPENDENT CONSULTANT STATUS. CONSULTANT and COMMISSION have reviewed and
38. INSPECTION OF WORK
39. INSURANCE. CONSULTANT, at its sole cost and expense, for the full term of this Agreement, and any
40. Independent Contractors. The parties are independent contractors, and nothing
41. Itemized expenses incurred during the billing period;
42. Job description
43. LICENSES. If a license of any kind is required of CONSULTANT, its employees, agents, or sub
44. Labor (staff name, hours charged, hourly billing rate, current charges and cumulative
45. MODIFICATION OF AGREEMENT.
46. Maternity leave (See Guideline 12)
47. Meal Intervals (See Guideline 7)
48. Miscellaneous.
49. NONASSIGNMENT. The CONSULTANT shall not assign the Agreement without the prior written consent
50. NOTIFICATION. All notices hereunder and communications regarding interpretation of the terms of this
51. No Representations Made. Recipient acknowledges that neither Discloser, nor
52. No Rights Granted. Nothing in this Agreement shall be construed as granting
53. Nondisclosure of Confidential Information. Recipient shall not use any
54. Notice of Compelled Disclosure. In the event that Recipient or any person to
55. Notices. All notices required or permitted to be made under this Agreement shall be in writing and delivered
56. Other conditions of employment or benefits
57. Parties.
58. Place of work
59. Possession And Condition Of Premises. At the time for performance the Premises also shall comply with
60. Public Holidays (See Guideline 9)
61. Purchase Price. ThepurchasepriceforthePremises is $
62. REBATES, KICKBACKS OR OTHER UNLAWFUL CONSIDERATION. The CONSULTANT
63. RETENTION AND AUDIT OF RECORDS. For the purpose of determining compliance with Public
64. Remedies. Each party’s obligations set forth in this Agreement are necessary and
65. Report of expenditures by CONSULTANT and subconsultants for each task and subtask
66. Return of Materials. Recipient shall, except as otherwise expressly authorized
67. SAFETY
68. SUBCONTRACTING
69. Sick leave (See Guideline 11)
70. Sunday work (See Guideline 8)
71. TERM. This Agreement shall take effect on (DATE); contingent upon prior approval by the
72. Term. The foregoing commitments of each party shall survive any termination of
73. Termination of employment (See Guidelines 2 and 3)
74. Tests/Survey. (Delete If Waived) The BUYER'S obligations under this Agreement are subject to BUYER'S
75. Time For Performance. The SELLER shall deliver the deed and the BUYER shall pay the balance of the
76. Title Insurance. BUYER'S obligations are contingent upon the availability (at normal premium rates) of an
77. Title/Plans. The SELLER shall convey the Premises by a good and sufficient quitclaim deed running to the
78. Total amount previously paid under this Agreement;
79. Total invoice/payment requested;
80. WORK PRODUCTS. All material, data, information, and written, graphic or other work produced under
81. Wage (See Guidelines 4 and 5)
82. Warranties And Representations. The SELLER further represents and warrants that SELLER has full
83. Written progress reports, in a format to be mutually agreed upon, that is sufficiently

In [26]:
def assign_category(label):

    label = label.lower()

    if any(x in label for x in [
        "payment",
        "compensation",
        "wage",
        "fee",
        "escrow",
        "purchase price",
        "remuneration"
    ]):
        return "Payment"

    elif any(x in label for x in [
        "confidential",
        "non disclosure"
    ]):
        return "Confidentiality"

    elif any(x in label for x in [
        "leave",
        "employee",
        "employment",
        "clothing",
        "accommodation"
    ]):
        return "Employment"

    elif any(x in label for x in [
        "warranty",
        "indemnification",
        "liability",
        "damages"
    ]):
        return "Liability"

    elif any(x in label for x in [
        "premises",
        "deed",
        "property"
    ]):
        return "Property"

    elif any(x in label for x in [
        "law",
        "dispute",
        "agreement",
        "jurisdiction"
    ]):
        return "Legal"

    elif any(x in label for x in [
        "copyright",
        "trademark",
        "work products",
        "license"
    ]):
        return "Intellectual_Property"

    elif any(x in label for x in [
        "duties",
        "performance",
        "reports",
        "commencement"
    ]):
        return "Performance"

    elif any(x in label for x in [
        "termination",
        "default"
    ]):
        return "Termination"

    else:
        return "General"

In [27]:
df["category"] = df["label"].apply(
    assign_category
)

print(
    df["category"].value_counts()
)

category
General                  32
Legal                    17
Employment               10
Payment                   8
Property                  5
Performance               4
Confidentiality           3
Termination               2
Liability                 1
Intellectual_Property     1
Name: count, dtype: int64

In [28]:
print(df["category"].value_counts())

category
General                  32
Legal                    17
Employment               10
Payment                   8
Property                  5
Performance               4
Confidentiality           3
Termination               2
Liability                 1
Intellectual_Property     1
Name: count, dtype: int64

In [30]:
df.to_csv(
   r"D:\contract-intelligence-ai\data\processed\cuad_training.csv",
    index=False
)

print("Saved Successfully")

Saved Successfully

In [32]:
import pandas as pd

df = pd.read_csv(
    r"D:\contract-intelligence-ai\data\processed\cuad_training.csv",
)

print(df.shape)

print(df.head())

(83, 3)
                                               label  \
0                                           Parties.
1  Description Of Premises. Thepremises (the "Pre...
2  Purchase Price. ThepurchasepriceforthePremises...
3  Escrow. All funds deposited or paid by the BUY...
4  Time For Performance. The SELLER shall deliver...

                                                text  category
0  1. Parties.\n[insert name],\nthe "SELLER," agr...   General
1  2. Description Of Premises. Thepremises (the "...  Property
2  3. Purchase Price. ThepurchasepriceforthePremi...   Payment
3  4. Escrow. All funds deposited or paid by the ...   Payment
4  5. Time For Performance. The SELLER shall deli...  Property

In [33]:
print(df["label"].value_counts().head(50))

label
Parties.                                                                                                        1
COMPLETE AGREEMENT                                                                                              1
REBATES, KICKBACKS OR OTHER UNLAWFUL CONSIDERATION. The CONSULTANT                                              1
NONASSIGNMENT. The CONSULTANT shall not assign the Agreement without the prior written consent                  1
SUBCONTRACTING                                                                                                  1
AUDIT REVIEW PROCEDURES                                                                                         1
DISPUTES. This Agreement shall be construed under the laws of the State of California. Pending final            1
MODIFICATION OF AGREEMENT.                                                                                      1
SAFETY                                                                                                          1
WORK PRODUCTS. All material, data, information, and written, graphic or other work produced under               1
ACKNOWLEDGMENT. CONSULTANT shall acknowledge in all reports and literature that the material is                 1
INSPECTION OF WORK                                                                                              1
RETENTION AND AUDIT OF RECORDS. For the purpose of determining compliance with Public                           1
INDEPENDENT CONSULTANT STATUS. CONSULTANT and COMMISSION have reviewed and                                      1
LICENSES. If a license of any kind is required of CONSULTANT, its employees, agents, or sub                     1
HARASSMENT. The COMMISSION maintains a strict policy prohibiting unlawful harassment, including                 1
EQUAL EMPLOYMENT OPPORTUNITY. During and in relation to the performance of this Agreement,                      1
FEDERAL, STATE AND LOCAL LAWS. CONSULTANT warrants that in the performance of this                              1
INSURANCE. CONSULTANT, at its sole cost and expense, for the full term of this Agreement, and any               1
NOTIFICATION. All notices hereunder and communications regarding interpretation of the terms of this            1
CONSULTANT 2. SANTA CRUZ COUNTY REGIONAL                                                                        1
EARLY TERMINATION.                                                                                              1
APPROVED AS TO INSURANCE: 4. APPROVED AS TO FORM:                                                               1
Other conditions of employment or benefits                                                                      1
Clothing (Delete this clause if not applicable)                                                                 1
Accommodation                                                                                                   1
Deductions from remuneration (See Guideline 14)                                                                 1
Family responsibility leave (See Guideline 13)                                                                  1
Maternity leave (See Guideline 12)                                                                              1
Sick leave (See Guideline 11)                                                                                   1
Annual Leave (See Guideline 10)                                                                                 1
Public Holidays (See Guideline 9)                                                                               1
Sunday work (See Guideline 8)                                                                                   1
Meal Intervals (See Guideline 7)                                                                                1
Hours of work (See Guideline 6)                                                                                 1
Wage (See Guidelines 4 and 5)                                                                                   1
Termination of employment (See Guidelines 2 and 3)                                                              1
Job description                                                                                                 1
Place of work                                                                                                   1
Commencement                                                                                                    1
INDEMNIFICATION FOR DAMAGES, TAXES AND CONTRIBUTIONS.                                                           1
TERM. This Agreement shall take effect on (DATE); contingent upon prior approval by the                         1
Description Of Premises. Thepremises (the "Premises")consist oftheland containing approximately                 1
Definition of Confidential Information. “Confidential Information” means                                        1
Counterparts / Facsimiles / Construction Of Agreement. This Agreement may be executed in                        1
Notices. All notices required or permitted to be made under this Agreement shall be in writing and delivered    1
Warranties And Representations. The SELLER further represents and warrants that SELLER has full                 1
Tests/Survey. (Delete If Waived) The BUYER'S obligations under this Agreement are subject to BUYER'S            1
Buyer's Financing. (Delete if Waived) The BUYER'S obligation to purchase is conditioned upon obtaining          1
Buyer's Default. If the BUYER or BUYER'S nominee breaches this Agreement, all escrowed funds paid or            1
Name: count, dtype: int64

In [34]:
print(df["label"].value_counts().head(50))

label
Parties.                                                                                                        1
COMPLETE AGREEMENT                                                                                              1
REBATES, KICKBACKS OR OTHER UNLAWFUL CONSIDERATION. The CONSULTANT                                              1
NONASSIGNMENT. The CONSULTANT shall not assign the Agreement without the prior written consent                  1
SUBCONTRACTING                                                                                                  1
AUDIT REVIEW PROCEDURES                                                                                         1
DISPUTES. This Agreement shall be construed under the laws of the State of California. Pending final            1
MODIFICATION OF AGREEMENT.                                                                                      1
SAFETY                                                                                                          1
WORK PRODUCTS. All material, data, information, and written, graphic or other work produced under               1
ACKNOWLEDGMENT. CONSULTANT shall acknowledge in all reports and literature that the material is                 1
INSPECTION OF WORK                                                                                              1
RETENTION AND AUDIT OF RECORDS. For the purpose of determining compliance with Public                           1
INDEPENDENT CONSULTANT STATUS. CONSULTANT and COMMISSION have reviewed and                                      1
LICENSES. If a license of any kind is required of CONSULTANT, its employees, agents, or sub                     1
HARASSMENT. The COMMISSION maintains a strict policy prohibiting unlawful harassment, including                 1
EQUAL EMPLOYMENT OPPORTUNITY. During and in relation to the performance of this Agreement,                      1
FEDERAL, STATE AND LOCAL LAWS. CONSULTANT warrants that in the performance of this                              1
INSURANCE. CONSULTANT, at its sole cost and expense, for the full term of this Agreement, and any               1
NOTIFICATION. All notices hereunder and communications regarding interpretation of the terms of this            1
CONSULTANT 2. SANTA CRUZ COUNTY REGIONAL                                                                        1
EARLY TERMINATION.                                                                                              1
APPROVED AS TO INSURANCE: 4. APPROVED AS TO FORM:                                                               1
Other conditions of employment or benefits                                                                      1
Clothing (Delete this clause if not applicable)                                                                 1
Accommodation                                                                                                   1
Deductions from remuneration (See Guideline 14)                                                                 1
Family responsibility leave (See Guideline 13)                                                                  1
Maternity leave (See Guideline 12)                                                                              1
Sick leave (See Guideline 11)                                                                                   1
Annual Leave (See Guideline 10)                                                                                 1
Public Holidays (See Guideline 9)                                                                               1
Sunday work (See Guideline 8)                                                                                   1
Meal Intervals (See Guideline 7)                                                                                1
Hours of work (See Guideline 6)                                                                                 1
Wage (See Guidelines 4 and 5)                                                                                   1
Termination of employment (See Guidelines 2 and 3)                                                              1
Job description                                                                                                 1
Place of work                                                                                                   1
Commencement                                                                                                    1
INDEMNIFICATION FOR DAMAGES, TAXES AND CONTRIBUTIONS.                                                           1
TERM. This Agreement shall take effect on (DATE); contingent upon prior approval by the                         1
Description Of Premises. Thepremises (the "Premises")consist oftheland containing approximately                 1
Definition of Confidential Information. “Confidential Information” means                                        1
Counterparts / Facsimiles / Construction Of Agreement. This Agreement may be executed in                        1
Notices. All notices required or permitted to be made under this Agreement shall be in writing and delivered    1
Warranties And Representations. The SELLER further represents and warrants that SELLER has full                 1
Tests/Survey. (Delete If Waived) The BUYER'S obligations under this Agreement are subject to BUYER'S            1
Buyer's Financing. (Delete if Waived) The BUYER'S obligation to purchase is conditioned upon obtaining          1
Buyer's Default. If the BUYER or BUYER'S nominee breaches this Agreement, all escrowed funds paid or            1
Name: count, dtype: int64

In [35]:
labels = sorted(df["label"].unique())

for label in labels[:100]:
    print(label)

ACKNOWLEDGMENT. CONSULTANT shall acknowledge in all reports and literature that the material is
APPROVED AS TO INSURANCE: 4. APPROVED AS TO FORM:
AUDIT REVIEW PROCEDURES
Acceptance Of Deed. The BUYER shall have the right to accept such title to the Premises as the SELLER
Accommodation
Acknowledgment Of Fee Due Broker. The SELLER and BUYER acknowledge that a fee of
Additional Provisions.
Adjustments. At the time for performance of this Agreement adjustments shall be made as of the date of
Annual Leave (See Guideline 10)
Buyer's Default. If the BUYER or BUYER'S nominee breaches this Agreement, all escrowed funds paid or
Buyer's Financing. (Delete if Waived) The BUYER'S obligation to purchase is conditioned upon obtaining
COMPENSATION.
COMPLETE AGREEMENT
CONSULTANT 2. SANTA CRUZ COUNTY REGIONAL
CONSULTANT's final invoice must be submitted within 60-calendar days after
Closing Certifications and Documents. The SELLER shall execute and deliver simultaneously with the
Clothing (Delete this clause if not applicable)
Commencement
Common Interest Agreement. To the extent that any Confidential Information
Counterparts / Facsimiles / Construction Of Agreement. This Agreement may be executed in
DISPUTES. This Agreement shall be construed under the laws of the State of California. Pending final
DUTIES.
Deductions from remuneration (See Guideline 14)
Definition of Confidential Information. “Confidential Information” means
Description Of Premises. Thepremises (the "Premises")consist oftheland containing approximately
EARLY TERMINATION.
EQUAL EMPLOYMENT OPPORTUNITY. During and in relation to the performance of this Agreement,
Escrow. All funds deposited or paid by the BUYER shall be held in a non-interest bearing escrow account,
Exceptions. Notwithstanding the above, information disclosed hereunder shall
Extension Of Time For Performance. If the SELLER cannot convey title as required by this Agreement or
FEDERAL, STATE AND LOCAL LAWS. CONSULTANT warrants that in the performance of this
Family responsibility leave (See Guideline 13)
General
HARASSMENT. The COMMISSION maintains a strict policy prohibiting unlawful harassment, including
Hours of work (See Guideline 6)
INDEMNIFICATION FOR DAMAGES, TAXES AND CONTRIBUTIONS.
INDEPENDENT CONSULTANT STATUS. CONSULTANT and COMMISSION have reviewed and
INSPECTION OF WORK
INSURANCE. CONSULTANT, at its sole cost and expense, for the full term of this Agreement, and any
Independent Contractors. The parties are independent contractors, and nothing
Itemized expenses incurred during the billing period;
Job description
LICENSES. If a license of any kind is required of CONSULTANT, its employees, agents, or sub
Labor (staff name, hours charged, hourly billing rate, current charges and cumulative
MODIFICATION OF AGREEMENT.
Maternity leave (See Guideline 12)
Meal Intervals (See Guideline 7)
Miscellaneous.
NONASSIGNMENT. The CONSULTANT shall not assign the Agreement without the prior written consent
NOTIFICATION. All notices hereunder and communications regarding interpretation of the terms of this
No Representations Made. Recipient acknowledges that neither Discloser, nor
No Rights Granted. Nothing in this Agreement shall be construed as granting
Nondisclosure of Confidential Information. Recipient shall not use any
Notice of Compelled Disclosure. In the event that Recipient or any person to
Notices. All notices required or permitted to be made under this Agreement shall be in writing and delivered
Other conditions of employment or benefits
Parties.
Place of work
Possession And Condition Of Premises. At the time for performance the Premises also shall comply with
Public Holidays (See Guideline 9)
Purchase Price. ThepurchasepriceforthePremises is $
REBATES, KICKBACKS OR OTHER UNLAWFUL CONSIDERATION. The CONSULTANT
RETENTION AND AUDIT OF RECORDS. For the purpose of determining compliance with Public
Remedies. Each party’s obligations set forth in this Agreement are necessary and
Report of expenditures by CONSULTANT and subconsultants for each task and subtask
Return of Materials. Recipient shall, except as otherwise expressly authorized
SAFETY
SUBCONTRACTING
Sick leave (See Guideline 11)
Sunday work (See Guideline 8)
TERM. This Agreement shall take effect on (DATE); contingent upon prior approval by the
Term. The foregoing commitments of each party shall survive any termination of
Termination of employment (See Guidelines 2 and 3)
Tests/Survey. (Delete If Waived) The BUYER'S obligations under this Agreement are subject to BUYER'S
Time For Performance. The SELLER shall deliver the deed and the BUYER shall pay the balance of the
Title Insurance. BUYER'S obligations are contingent upon the availability (at normal premium rates) of an
Title/Plans. The SELLER shall convey the Premises by a good and sufficient quitclaim deed running to the
Total amount previously paid under this Agreement;
Total invoice/payment requested;
WORK PRODUCTS. All material, data, information, and written, graphic or other work produced under
Wage (See Guidelines 4 and 5)
Warranties And Representations. The SELLER further represents and warrants that SELLER has full
Written progress reports, in a format to be mutually agreed upon, that is sufficiently

In [36]:
import pandas as pd

df = pd.read_csv(
     r"D:\contract-intelligence-ai\data\processed\cuad_training.csv",
)

print(
    df["clean_label"].value_counts().head(50)
)

KeyError: 'clean_label'

In [37]:
import pandas as pd

df = pd.read_csv(
    r"D:\contract-intelligence-ai\data\processed\cuad_training.csv"
)

def clean_label(label):

    label = str(label)

    if "." in label:
        label = label.split(".")[0]

    return label.strip()

df["clean_label"] = df["label"].apply(clean_label)

print(df[["label", "clean_label"]].head())

                                               label              clean_label
0                                           Parties.                  Parties
1  Description Of Premises. Thepremises (the "Pre...  Description Of Premises
2  Purchase Price. ThepurchasepriceforthePremises...           Purchase Price
3  Escrow. All funds deposited or paid by the BUY...                   Escrow
4  Time For Performance. The SELLER shall deliver...     Time For Performance

In [38]:
print(df["clean_label"].value_counts().head(30))

clean_label
Parties                                               1
COMPLETE AGREEMENT                                    1
REBATES, KICKBACKS OR OTHER UNLAWFUL CONSIDERATION    1
NONASSIGNMENT                                         1
SUBCONTRACTING                                        1
AUDIT REVIEW PROCEDURES                               1
DISPUTES                                              1
MODIFICATION OF AGREEMENT                             1
SAFETY                                                1
WORK PRODUCTS                                         1
ACKNOWLEDGMENT                                        1
INSPECTION OF WORK                                    1
RETENTION AND AUDIT OF RECORDS                        1
INDEPENDENT CONSULTANT STATUS                         1
LICENSES                                              1
HARASSMENT                                            1
EQUAL EMPLOYMENT OPPORTUNITY                          1
FEDERAL, STATE AND LOCAL LAWS                         1
INSURANCE                                             1
NOTIFICATION                                          1
CONSULTANT 2                                          1
EARLY TERMINATION                                     1
APPROVED AS TO INSURANCE: 4                           1
Other conditions of employment or benefits            1
Clothing (Delete this clause if not applicable)       1
Accommodation                                         1
Deductions from remuneration (See Guideline 14)       1
Family responsibility leave (See Guideline 13)        1
Maternity leave (See Guideline 12)                    1
Sick leave (See Guideline 11)                         1
Name: count, dtype: int64

In [39]:
df.to_csv(
    r"D:\contract-intelligence-ai\data\processed\cuad_training_cleaned.csv",
    index=False
)

print("Saved Successfully")

Saved Successfully

In [40]:
print(df["clean_label"].value_counts().head(30))

clean_label
Parties                                               1
COMPLETE AGREEMENT                                    1
REBATES, KICKBACKS OR OTHER UNLAWFUL CONSIDERATION    1
NONASSIGNMENT                                         1
SUBCONTRACTING                                        1
AUDIT REVIEW PROCEDURES                               1
DISPUTES                                              1
MODIFICATION OF AGREEMENT                             1
SAFETY                                                1
WORK PRODUCTS                                         1
ACKNOWLEDGMENT                                        1
INSPECTION OF WORK                                    1
RETENTION AND AUDIT OF RECORDS                        1
INDEPENDENT CONSULTANT STATUS                         1
LICENSES                                              1
HARASSMENT                                            1
EQUAL EMPLOYMENT OPPORTUNITY                          1
FEDERAL, STATE AND LOCAL LAWS                         1
INSURANCE                                             1
NOTIFICATION                                          1
CONSULTANT 2                                          1
EARLY TERMINATION                                     1
APPROVED AS TO INSURANCE: 4                           1
Other conditions of employment or benefits            1
Clothing (Delete this clause if not applicable)       1
Accommodation                                         1
Deductions from remuneration (See Guideline 14)       1
Family responsibility leave (See Guideline 13)        1
Maternity leave (See Guideline 12)                    1
Sick leave (See Guideline 11)                         1
Name: count, dtype: int64

In [42]:
import pandas as pd

df = pd.read_csv(
    r"D:\contract-intelligence-ai\data\processed\cuad_training_cleaned.csv",
)

print(df.columns)

print(df.head())

Index(['label', 'text', 'category', 'clean_label'], dtype='object')
                                               label  \
0                                           Parties.
1  Description Of Premises. Thepremises (the "Pre...
2  Purchase Price. ThepurchasepriceforthePremises...
3  Escrow. All funds deposited or paid by the BUY...
4  Time For Performance. The SELLER shall deliver...

                                                text  category  \
0  1. Parties.\n[insert name],\nthe "SELLER," agr...   General
1  2. Description Of Premises. Thepremises (the "...  Property
2  3. Purchase Price. ThepurchasepriceforthePremi...   Payment
3  4. Escrow. All funds deposited or paid by the ...   Payment
4  5. Time For Performance. The SELLER shall deli...  Property

               clean_label
0                  Parties
1  Description Of Premises
2           Purchase Price
3                   Escrow
4     Time For Performance

In [43]:
import pandas as pd

df = pd.read_csv(
     r"D:\contract-intelligence-ai\data\processed\cuad_training_cleaned.csv",
)

print(df.shape)

print(df["category"].value_counts())

(83, 4)
category
General                  32
Legal                    17
Employment               10
Payment                   8
Property                  5
Performance               4
Confidentiality           3
Termination               2
Liability                 1
Intellectual_Property     1
Name: count, dtype: int64

In [44]:
print(df.shape)

print(df["category"].value_counts())

(83, 4)
category
General                  32
Legal                    17
Employment               10
Payment                   8
Property                  5
Performance               4
Confidentiality           3
Termination               2
Liability                 1
Intellectual_Property     1
Name: count, dtype: int64

In [46]:
import pandas as pd

cuad_df = pd.read_csv(
    r"D:\contract-intelligence-ai\data\processed\cuad_100_categorized.csv"
)

print(cuad_df.shape)

print(cuad_df["category"].value_counts())

(1571, 4)
category
General                  915
Legal                    242
Payment                   94
Termination               87
Liability                 75
Intellectual_Property     51
Confidentiality           50
Property                  29
Performance               22
Employment                 6
Name: count, dtype: int64

In [47]:
import pandas as pd

cuad_df = pd.read_csv(
    r"D:\contract-intelligence-ai\data\processed\cuad_100_categorized.csv"
)

local_df = pd.read_csv(
    r"D:\contract-intelligence-ai\data\processed\cuad_training.csv"
)

final_df = pd.concat(
    [cuad_df, local_df],
    ignore_index=True
)

final_df.to_csv(
    r"D:\contract-intelligence-ai\data\processed\final_training_dataset.csv",
    index=False
)

print(final_df.shape)

(1654, 4)

In [48]:
df = pd.read_csv(
    r"D:\contract-intelligence-ai\data\processed\final_training_dataset.csv"
)

print(df.shape)

print(df["category"].value_counts())

(1654, 4)
category
General                  947
Legal                    259
Payment                  102
Termination               89
Liability                 76
Confidentiality           53
Intellectual_Property     52
Property                  34
Performance               26
Employment                16
Name: count, dtype: int64

In [49]:
import transformers
import torch

print(transformers.__version__)
print(torch.__version__)

4.55.4
2.12.1+cpu